language: python

jobs:
  include:
    - name: "CI on Windows/Python3.6"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.2
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "CI on MacOS/Python3.6"
      os: osx
      language: shell
    - name: "CI on Linux/Python3.6"
      os: linux
      python: 3.6
      script: /bin/bash ./scripts/check_code_style.sh

env:
  - PYTHONPATH=${PWD}

install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      pip3 install --upgrade paddlepaddle;
      pip3 install -r requirements.txt;
    else
      pip install --upgrade paddlepaddle;
      pip install -r requirements.txt;
      pip install yapf==0.26.0;
    fi

notifications:
  email:
    on_success: change
    on_failure: always
