name: faster_rcnn_resnet50_fpn_venus
dir: "modules/image/object_detection/faster_rcnn_resnet50_fpn_venus"
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/cv/faster_rcnn_resnet50_fpn_venus_model.tar.gz
    dest: faster_rcnn_resnet50_fpn_model
    uncompress: True
