name: resnet50_vd_animals
dir: "modules/image/classification/fix_resnext101_32x48d_wsl_imagenet"
exclude:
  - README.md
resources:
  -
    url: https://bj.bcebos.com/paddlehub/hub_dev/fix_resnext101_32x48d_wsl_imagenet_model.tar.gz
    dest: model
    uncompress: True
