name: yolov3_darknet53_venus
dir: "modules/image/object_detection/yolov3_darknet53_venus"
# resources:
#   -
#     url: https://paddlehub.bj.bcebos.com/model/cv/yolov3_darknet53_model.tar.gz
#     dest: yolov3_darknet53_model
#     uncompress: True
