name: yolov3_resnet34_coco2017
dir: "modules/image/object_detection/yolov3_resnet34_coco2017"
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/cv/yolov3_resnet34_model.tar.gz
    dest: yolov3_resnet34_model
    uncompress: True
